### ISSUE TITLE
Look through use-cases to make sure all scenarios are covered

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#1]
Erik look through all use-cases in earlier revisions. We need to do that again and make sure that we still solve all of them. Preferably by specifying how it's profiled for the specific use-cases using, for example, DTLS, object security, dynamic client registration and uma.

**Comment by LudwigSeitz** [comment]
I've started on this. I'm through with container monitoring and home automation ... I'll send the results around for comments once I'm done.

**Comment by erwah** [comment]
Shared a google docs with my old review. It was sadly not from the latest drafts but it might still give at least some input for your work.

**Comment by LudwigSeitz** [comment]
On 2015-12-02 17:00, Erik Wahlström wrote:
> Shared a google docs with my old review. It was sadly not from the
> latest drafts but it might still give at least some input for your work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LudwigSeitz/ace-oauth/issues/1#issuecomment-161344760>.
>

Ok that's on a quite different level than what I started doing yesterday 
... back to the drawing board.

/Ludwig

-- 
Ludwig Seitz, PhD
SICS Swedish ICT AB
Ideon Science Park
Building Beta 2
Scheelevägen 17
SE-223 70 Lund

Phone +46(0)70-349 92 51
http://www.sics.se

**Comment by LudwigSeitz** [comment]
Done modulo reviews.

**Comment by LudwigSeitz** [comment]
Erik is reviewing. No major issues, I'm closing this.
