### ISSUE TITLE
Reference-tokens.

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#11]
Define reference tokens and the security property needed to handle them.

**Comment by LudwigSeitz** [comment]
This is for the the introspection profile.

**Comment by LudwigSeitz** [comment]
As per discussion this seems to go into the framework anyways.

**Comment by LudwigSeitz** [comment]
Should we define a token-type for this? Or is it the type of token that is referenced instead?

**Comment by LudwigSeitz** [comment]
Should be defined by the application.
