### ISSUE TITLE
Open up for extensions to the Deployment option section

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#14]
Open up for extensions to the Deployment option section so it’s possible to write profiles in the future (mix http and coap).

**Comment by LudwigSeitz** [comment]
My take was that the current deployment options section was just a number of non-exhaustive suggestions. How do you propose we make this more obvious?

**Comment by erwah** [comment]
How about if we add one new section to the deployment options that talk about other potential deployment options in a non normative way that might be added in extensions.

**Comment by LudwigSeitz** [comment]
Profiles will now be written as per WG decision at IETF 95
