### ISSUE TITLE
Sign clients requests against token endpoint

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#19]
draft-ietf-oauth-jwsreq-06 defines how JWT is used by client against AS. This could be used in a hop-by-hop scenario. Also see how it's done in CWT.

**Comment by LudwigSeitz** [comment]
This should go into a profile, since it depends on the protocol used between C and AS (CoAP vs HTTP).

**Comment by LudwigSeitz** [comment]
It appears this might still go into the framework as per our discussion.

**Comment by LudwigSeitz** [comment]
There is now a requirement in the framework to use secure communications between client and AS, this should take care of the above.
