### ISSUE TITLE
Decide what we should start profiling in detail.

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#2]
Go through document and make sure that we have a backlog of items to be profiled.

**Comment by LudwigSeitz** [comment]
From the draft ToC we have:
-Communication security protocol (Client Information in response to the token request). This is covered by #21 and #4.
-Authorization Information Resource at the RS. This is covered by #5.
-AIF. This is currently covered by draft-borman-core-ace-aif. Also covered by #20.
-CBOR data formats. Currently covered in appendix C. I'm opening a new issue for that.
