### ISSUE TITLE
Write extension to the introspection endpoint so that it communicates keys and also “aif”.

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#20]
The http based introspection endpoint don't have a registry of attributes to send back in a response. Both aif and a key should be returned.

**Comment by LudwigSeitz** [comment]
FYI: We (Erik, Samuel, Ludwig) decided that this and Introspection should be in the main draft.

**Comment by LudwigSeitz** [comment]
This depends on #14 we will close this as soon as we have made a decision on #14

**Comment by LudwigSeitz** [comment]
This goes into the introspection profile.

**Comment by LudwigSeitz** [comment]
As per our discussion it does go into the framework.

**Comment by LudwigSeitz** [comment]
We removed aif and defined how the introspection endpoint communicates keys
