### ISSUE TITLE
Discovery of AS

### ISSUE THREAD

**Issue by samuelerdtman** [LudwigSeitz/ace-oauth#22]
Investigate and describe how discovery can be made, for Bluetooth Smart it might be broad cast data and services, for CoAP broadcast and link directory might be a solution to indicate where to request authorisation.

**Comment by samuelerdtman** [comment]
https://mailarchive.ietf.org/arch/msg/ace/BClpJNwVZT-eY5na82Cd_jjOSHg

- For the description in this document we assume that the client has been registered to an AS.  Registration means that the two share credentials, configuration parameters and that some form of authorization has taken place.  These credentials are used to protect the token request by the client and the transport of access tokens and client information from AS to the client.
- MS: To me this fairly complex and needs to be described better. I understand that this document may not standardize how the client discovers and registers to an AS, but there still needs to be some description on how this is done in practice. While currently a client can discover an RS (resource-server) using a resource directory or DNS Service discovery, how does it find out which AS is responsible for the given RS. In the web-world this works rather well with re-directs but I am not sure how this would work in the scenarios described in the draft. I see a related issue on git as well: https://github.com/LudwigSeitz/ace-oauth/issues/22

**Comment by LudwigSeitz** [comment]
I would rather have AS discovery defined in a different document. If no one disagrees I will close this issue soon.
