### ISSUE TITLE
Client using keys with multiple RS:es

### ISSUE THREAD

**Issue by erdtman** [LudwigSeitz/ace-oauth#26]
https://mailarchive.ietf.org/arch/msg/ace/BClpJNwVZT-eY5na82Cd_jjOSHg
- A: The client first generates a public-private key pair used for communication security with the RS.
- MS: Does the client generate a new key pair for every RS. Can they be re-used across RS? I assume key generation can be expensive for some devices?

Samuel: In general I would say that the client can use the same key pair with multiple RSes, but should know the security and privacy implications. e.g. privacy wise it would be possible for RSes to track the Client in a way that is not desirable and security wise the key would need to rotate more often. I have added an issue to add text regarding this.

**Comment by LudwigSeitz** [comment]
This should go into the security considerations.

**Comment by LudwigSeitz** [comment]
... rather privacy considerations
