### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#27]
Add text that describes error handling and what errors to send from AS and RS.

**Comment by LudwigSeitz** [comment]
Including things like: What error to send when the client requests a type of PoP key that is not supported by the RS.

**Comment by LudwigSeitz** [comment]
Some of that is now done, but we need to review it.

**Comment by erdtman** [comment]
still think it is a bit wage 
it says in section 6.1.  Client-to-AS Request
for profile "the AS MUST reply with an error message."
and for cnf "the AS MUST respond with an error message."
But do we need to define new error codes/messages?

**Comment by LudwigSeitz** [comment]
I am planning to rewrite section 6 today or tomorrow, I think this will fix several issues, this one included.
