### ISSUE TITLE
Register CoAP option for Access Token

### ISSUE THREAD

**Issue by samuelerdtman** [LudwigSeitz/ace-oauth#28]
if access token is smaller then 255 bytes it can in some cases be preferable to send as an option instead of sending it in a separate request to the authorization information resource on the RS.

**Comment by LudwigSeitz** [comment]
Right, we need to define what the RS is supposed to do in that case (basically I'd say, treat it as if there was a separate request to the authorization resource with the content of that option as payload, what do you think?)

**Comment by LudwigSeitz** [comment]
This belongs into the corresponding profile.
