### ISSUE TITLE
Extend 'cnf' to also carry information about certificates

### ISSUE THREAD

**Issue by LudwigSeitz** [LudwigSeitz/ace-oauth#36]
We should consider extending 'cnf' to also carry information about certificates for those people who want to use them.

**Comment by LudwigSeitz** [comment]
For example this could be information about a trust anchor

**Comment by LudwigSeitz** [comment]
Or a certificate fingerprint.

**Comment by erdtman** [comment]
look at DANE (https://tools.ietf.org/html/rfc6698) and pinning (https://tools.ietf.org/html/rfc7469)

**Comment by LudwigSeitz** [comment]
Seems like we should wait for Jim Schaad's spec to specify how to carry certs in COSE.

**Comment by LudwigSeitz** [comment]
Seems moot to me since the consensus looks like mirroring RFC 7800, which doesn't talk about certificates.
