### ISSUE TITLE
Fix figure 25

### ISSUE THREAD

**Issue by LudwigSeitz** [LudwigSeitz/ace-oauth#45]
As per Renzo's comments:
How did the RS got the client_id and the client_secret? The previous message from C to RS is to the /authz-info endpoint, and this communication is not protected, so this information should not be sent over that channel.

**Comment by LudwigSeitz** [comment]
Also the cnf need to transport a whole key in this example case (also per Renzo's comments)

**Comment by LudwigSeitz** [comment]
We need to clarify that this is the client_id and client_secret of the RS.

**Comment by erdtman** [comment]
Should be resolved with latest commit
