### ISSUE TITLE
Specify assumptions on what a AS knows about the RS

### ISSUE THREAD

**Issue by LudwigSeitz** [LudwigSeitz/ace-oauth#50]
We should write something about what knowledge we assume to be at the AS about the RS's. E.g. we assume that the AS knows which profiles the RS supports.

**Comment by LudwigSeitz** [comment]
... and what it knows about the Client.

**Comment by erdtman** [comment]
see https://tools.ietf.org/html/draft-ietf-oauth-native-apps-06 for an example
