### ISSUE TITLE
10.6.  ACE Profile Registry, no initial content?

### ISSUE THREAD

**Issue by erdtman** [LudwigSeitz/ace-oauth#53]
However in the text "6.4.4.  Profile" there is example of three, should we not register those?

**Comment by LudwigSeitz** [comment]
I think the profiles should register their identifiers themselves. So I would tend to remove the table in 6.4.4. and instead add text that tells the profiles to register values for the profile they define.

**Comment by erdtman** [comment]
Sounds good to me

**Comment by LudwigSeitz** [comment]
Done.
