### ISSUE TITLE
Introspection draft

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#6]
Introspection draft, should we keep it standing alone or integrate it?. Also make sure that we can send keys and aif.

**Comment by LudwigSeitz** [comment]
I would integrate it, it seems to me this is a very important part of the solution.

**Comment by LudwigSeitz** [comment]
Depends on the solution of #14.

**Comment by LudwigSeitz** [comment]
This will become the introspection profile.
