### ISSUE TITLE
Make a list of what we expect profiles to specify

### ISSUE THREAD

**Issue by LudwigSeitz** [LudwigSeitz/ace-oauth#60]
We have some (normative?) text in the document about what we expect profiles to specify. We should  gather this information in one place (appendix) in form of a checklist.

**Comment by LudwigSeitz** [comment]
Done, but could be in the main document. Any thoughts?

**Comment by erdtman** [comment]
Looking at https://tools.ietf.org/html/draft-ietf-oauth-native-apps-06#appendix-A
One thing that I think we should do is to add references to the section that is normative.

**Comment by LudwigSeitz** [comment]
Looks correct. I think searching for "MUST" "SHOULD" etc should (no caps :-) ) give you the right pointers in the documents
