### ISSUE TITLE
Update normative text defining what to include in profiles

### ISSUE THREAD

**Issue by erdtman** [LudwigSeitz/ace-oauth#77]
There is text sprinkled over the document defining what is required and optional for a profile.

Most of the text is good but in some cases it is wage, we need to read the doc from top to bottom with the profile perspective and update with MUST, SHOULD, MAY etc. to make it clear what to include in a profile.

An example of a wage formulation could be "a profile is expected to ..."

When doing this make sure to keep appendix "Requirements on Profiles" in sync.

**Comment by LudwigSeitz** [comment]
Here's hoping that doing a search for "profile" will reveal all relevant places ...
