### ISSUE TITLE
Describe server authentication against client.

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#8]
It's a common question, how client authenticates the RS. We should make sure to define and explain that in detail.

Request from WG: https://mailarchive.ietf.org/arch/msg/ace/WM4jMy3i9SNeF7m6ncD66XpjNKM
"One main question that is only partly solved by other solutions is: How can a constrained client authenticate the other party?"

**Comment by LudwigSeitz** [comment]
This is now dependent on the credentials we use (RPK, PSK, X.509) and possibly on the comSec protocol (DTLS vs object security). I think that should go into the profiles
