### ISSUE TITLE
Do we need a registry of cnf methods?

### ISSUE THREAD

**Issue by LudwigSeitz** [LudwigSeitz/ace-oauth#85]
RFC 7800 defines such a registry in 6.2. Do we need an analogous registry for CWT?

**Comment by erdtman** [comment]
I would say we need to create a registry for mapping for existing cnf methods (to numbers). and then we need to register COSE keys as a cnf option and possible more.

**Comment by LudwigSeitz** [comment]
But there aren't any existing methods, since we are redefining everything from RFC 7800 with CBOR and COSE.
