### ISSUE TITLE
Should /token /introspect and /authorize be ./well-known?

### ISSUE THREAD

**Issue by LudwigSeitz** [LudwigSeitz/ace-oauth#92]
Should these endpoints be part of the ./well-known addresses? Comment by Jim.

**Comment by LudwigSeitz** [comment]
I'm increasingly convinced this should be the case and it should include /authz-info. I'm currently working on some implementation problems on how to handle resources that should not be subject to access control, which includes /authz-info, it would be easy if we could just gather all such resources under one heading, like ./well-known

**Comment by erdtman** [comment]
I have done some research an my opinion is to avoid this for now.
When reading up on well-known I can see that two ways of using is has evolved.
The first one is to have a path under well-known (/.well-known/ace) that returns a set of links to the resources/endpoints defined by the specification. (When reading the well-known RFC (rfc5785) this is how I would interpret it). In this case it would be easy to add well-known support later on.
The second solution is to place your resources/endpoints under the well-known prefix (/.well-known/ace/token) this is how EST has done it /.well-known/est/simpleenroll, /.well-known/est/cacerts etc. I think to mandate this solution is not good for the simple reason that the path becomes long and requires several unnecessary bytes.

Looking at the OAuth 2.0 framework I can see that they have not registered wellknown paths and also phrased the language around endpoints slightly differently. In out text we talk about the '/token' endpoint the slash gives the reader the impression that this is a standardized name while OAuth talks about the 'token' endpoint i.e. it can be named anything.

**Comment by LudwigSeitz** [comment]
Conclusion is that we avoid this for now.
